class LoanModel {
  final String employeeId;
  final String date;
  final int amount;
  final String journalId;
  LoanModel({
    required this.employeeId,
    required this.date,
    required this.amount,
    required this.journalId,
  });

  Map<String, dynamic> toJson() {
    var month = date.substring(5, 7);

    // ignore: prefer_collection_literals
    final Map<String, dynamic> json = Map<String, dynamic>();
    json['employee_id'] = employeeId;
    json['month'] =
        month[0] == "0" ? date.substring(6, 7) : date.substring(5, 7);
    json['year'] = date.substring(0, 4);
    json['amount'] = amount;
    json['journal_id'] = journalId;
    return json;
  }
}



// class Autogenerated {
//   String? name;
//   String? email;

//   Autogenerated({this.name, this.email});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//     email = json['email'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['name'] = this.name;
//     data['email'] = this.email;
//     return data;
//   }
// }
